version: '3.8'

services:
  redis:
    image: redis:latest
    container_name: redis_container
    ports:
      - "6379:6379"
    volumes:
      - redis:/data  
    networks:
      - backend_network

  postgres:
    image: postgres:13.5
    container_name: postgres_container
    environment:
      POSTGRES_USER: hieudh
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: nesttraindb
    ports:
      - "5432:5432"
    volumes:
      - postgres:/var/lib/postgresql/data  
    networks:
      - backend_network

volumes:
  redis:  
  postgres:  

networks:
  backend_network:
